### ISSUE TITLE
데이터베이스 설계

### ISSUE THREAD

**Issue by ghost** [ooo3345sjh/Kmarket#14]
- [x] ERD 작업하기
- [x] 테이블 설계하기

**Comment by ghost** [comment]
2022/12/09 까지 테이블 명세서를 참고하시어 작업하세요.
가급적 ERD 그려서 테이블 설계하시기 바랍니다.

**Comment by JGwanghou** [comment]
20221207 ERD 작업 시작합니다.

**Comment by ooo3345sjh** [comment]
2022/12/09
작업자 : 서정현
데이터베이스 설계 완료
